--- #YAML:1.0
name:               Apache2-Connection-XForwardedFor
version:            0.01
abstract:           Sets the connection remote_ip to X-Forwarded-For header
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    mod_perl2:  2.000005
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
